# config/starship.toml (Minimo)

format = """
$os$directory$git_branch$git_status$python$line_break$character
"""

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = "green"
symbol = "ğŸŒ± "

[python]
symbol = "ğŸ "

[os]
disabled = false
symbols.Debian = "ğŸ¥ "
symbols.Alpine = "ğŸ”ï¸ "
symbols.Fedora = "ğŸ© "